---
version: "3"
services:
 devopsdb:
   image: nagashankar8916/1project:dbim
   ports:
     - "3306:3306"
    deploy:
     replicas: 3 
    networks:
     - app_network

 application:
   image: nagashankar8916/1project:appimg
   ports:
     - "1111:8080"
   deploy:
    replicas: 3 
   depends_on:
     - "devopsdb"
    netwroks:
      - app_network
networks:
 app_network:
   driver: overlay
